### PR TITLE
Don't crash when using pytester in default mode

### PR DESCRIPTION
**Pull request by njsmith**
If you try to test a pytest plugin using the pytester module, and you
also have pytest-faulthandler installed, then currently it crashes
with obscure errors. The problem is that by default, pytester runs the
sub-pytest in-process, and the sub-pytest has sys.stderr set to a
_pytest.capture.CaptureIO object, which has a fileno method (so the
old hasattr(sys.stderr, "fileno") check passes), but if you try to
call this method then it raises io.UnsupportedOperation.

So this commit robustifies the sys.stderr.fileno() calling code to
handle both a missing fileno (as before), and it raising
UnsupportedOperation.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @njsmith! I will make a new release shortly!

**Comment by The-Compiler** [comment]
I've had the same issue, and just ended up passing `plugins=['no:faulthandler']` without investigating in detail. This helps indeed! 👍

**Comment by The-Compiler** [comment]
Oh, I'm wondering how straightforward it is to add a test for this, though. I guess we could have a subprocess-pytester with the plugin, and from there launch an in-process one?

**Comment by njsmith** [comment]
@The-Compiler Yeah, I spent a few minutes trying to figure out how to add a test, and then gave up because I couldn't think of one :-). Using pytester inside pytester seems like a workable idea, though!

**Comment by nicoddemus** [comment]
Indeed a test would be nice.

@njsmith `1.4.1` has been published with this fix, thanks!

**Pull request merged**
