### PR TITLE
Re-add support for Python 2.6 and 3.3

### PR DESCRIPTION
**Pull request by jayvdb**
Use tox-travis to run the test suite on versions
of Python according to the Travis build matrix.

Python 3.3 support was removed in 8648373, before v1.0.1.
Python 2.6 support was removed in 2cb9ba9, and is not yet
released.

The dependencies all support these versions, and they both
currently pass all tests.

### CODE REVIEW

**Comment by jayvdb** [comment]
The changes to tox.ini are non-essential, and will make the AppVeyor job take a little longer, and even fail if those versions are not available on AppVeyor.  Happy to remove it if desired.

**Comment by nicoddemus** [comment]
Thanks @jayvdb!

> The changes to tox.ini are non-essential, and will make the AppVeyor job take a little longer, and even fail if those versions are not available on AppVeyor. Happy to remove it if desired.

Can you elaborate? The changes seem fine to me, taking longer is natural since we are now testing two additional environments. Or do you mean something else?

**Comment by jayvdb** [comment]
No, that is all I meant.  AppVeyor doesnt have as many (and concurrent) job runners for OSS, so the delay can be annoying, but probably not a major problem for a slow moving project like this.

**Comment by nicoddemus** [comment]
Oh I agree, that's fine then! :smile:

**Pull request merged**
